### ISSUE TITLE
Potential bug with Installation

### ISSUE THREAD

**Issue by danielm710** [shahcompbio/single_cell_pipeline#151]
When I install and set up the conda environment as described in the INSTALL.md, I ran into a problem.

After setting up the conda environment and preparing the input.yaml file, I ran the command below:

```
single_cell alignment --input_yaml inputs.yaml \
--library_id A1234A --maxjobs 4 --nocleanup --sentinel_only \
--submit local --loglevel DEBUG \
--tmpdir temp --pipelinedir pipeline \
--out_dir output --bams_dir bams \
--sequencing_center test \
--config_override '{"refdir": "refdata"}'
```

After running the command, I received an error:
```
Traceback (most recent call last):
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/pypeliner/jobs.py", line 481, in __call__
            ret_value = func(*callset.args, **callset.kwargs)
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/single_cell/workflows/align/align_tasks.py", line 219, in align_lanes
            screen_detailed, screen_summary, fastqscreen_params,
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/single_cell/workflows/align/align_tasks.py", line 153, in align_pe
            filter_contaminated_reads=fastqscreen_params['filter_contaminated_reads'],
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/single_cell/workflows/align/fastqscreen.py", line 221, in organism_filter
            fastq_r1, fastq_r2, tempdir, params, docker_image=docker_image
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/single_cell/workflows/align/fastqscreen.py", line 104, in run_fastq_screen_paired_end
            pypeliner.commandline.execute(*cmd, docker_image=docker_image)
          File "/home/ubuntu/ALIGN/miniconda3/lib/python3.7/site-packages/pypeliner/commandline.py", line 77, in execute
            if docker_kwargs and docker_kwargs.get('docker_image') and 'docker' in context_cfg:
        TypeError: argument of type 'NoneType' is not iterable
```

It looks like Pypeliner assigns the default value of `None` to `context_config` parameter if the value is not provided by the user, which results in calling `in` operator on `None type` object, hence the above error.

I managed to fix this error locally by changing line 77 of `pypeliner/commandline.py`

```
context_cfg = pypeliner.helpers.GlobalState.get("context_config") # line 76

if docker_kwargs and docker_kwargs.get('docker_image') and 'docker' in context_cfg: # line 77; OLD
if docker_kwargs and context_cfg and docker_kwargs.get('docker_image') and 'docker' in context_cfg: # line 77; MODIFIED
```

I am not sure how robust this fix is, but I think it's worthwhile looking into this installation problem.

Thanks

**Comment by danielm710** [comment]
I re-installed the pipeline today as described in [here](https://github.com/shahcompbio/single_cell_pipeline/blob/master/docs/source/install.md), and now i run into a new error

```
/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:186: ConvergenceWarning: Convergence cycle detected
	  warnings.warn("Convergence cycle detected", ConvergenceWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:186: ConvergenceWarning: Convergence cycle detected
	  warnings.warn("Convergence cycle detected", ConvergenceWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:191: IterationLimitWarning: Maximum number of iterations (1000) reached.
	  ") reached.", IterationLimitWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/statsmodels/regression/quantile_regression.py:186: ConvergenceWarning: Convergence cycle detected
	  warnings.warn("Convergence cycle detected", ConvergenceWarning)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/scripts/correct_read_count.py:179: SettingWithCopyWarning: 
	A value is trying to be set on a copy of a slice from a DataFrame.
	Try using .loc[row_indexer,col_indexer] = value instead
	
	See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
	  df_dist_filter['lowess'] = lowess(df_dist_filter['distances'], df_dist_filter['quantiles'], frac=lowess_frac, return_sorted=False)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/numpy/core/fromnumeric.py:58: FutureWarning: 
	The current behaviour of 'Series.argmin' is deprecated, use 'idxmin'
	instead.
	The behavior of 'argmin' will be corrected to return the positional
	minimum in the future. For now, use 'series.values.argmin' or
	'np.argmin(np.array(values))' to get the position of the minimum
	row.
	  return bound(*args, **kwds)
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/scripts/correct_read_count.py:226: FutureWarning: 
	.ix is deprecated. Please use
	.loc for label based indexing or
	.iloc for positional indexing
	
	See the documentation here:
	http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
	  df.ix[df_regression.index, 'modal_quantile'] = df_regression['modal_quantile']
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/scripts/correct_read_count.py:227: FutureWarning: 
	.ix is deprecated. Please use
	.loc for label based indexing or
	.iloc for positional indexing
	
	See the documentation here:
	http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
	  df.ix[df_regression.index, 'modal_curve'] = df_regression['modal_curve']
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/scripts/correct_read_count.py:228: FutureWarning: 
	.ix is deprecated. Please use
	.loc for label based indexing or
	.iloc for positional indexing
	
	See the documentation here:
	http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
	  df.ix[df_regression.index, 'modal_corrected'] = df_regression['modal_corrected']
	/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/scripts/correct_read_count.py:232: SettingWithCopyWarning: 
	A value is trying to be set on a copy of a slice from a DataFrame
	
	See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
	  df['copy'][df['map'] < self.mappability] = float('NaN')
	Traceback (most recent call last):
	  File "/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/pypeliner/jobs.py", line 481, in __call__
	    ret_value = func(*callset.args, **callset.kwargs)
	  File "/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/tasks.py", line 138, in run_hmmcopy
	    docker_image
	  File "/home/ubuntu/test_hmmcopy/miniconda3/lib/python3.7/site-packages/single_cell/workflows/hmmcopy/tasks.py", line 94, in run_hmmcopy_script
	    pypeliner.commandline.execute(*cmd, docker_image=docker_image)
	TypeError: execute() got an unexpected keyword argument 'docker_image'
```

Recent changes to Pypeliner may have caused it

**Comment by diljotgrewal** [comment]
Hi,
we're changing quite a few things in the pipeline and we're deprecating the conda packages. Stay tuned for the new updated install guide.

In the mean time, installing v0.5.27 of pypeliner (https://github.com/shahcompbio/pypeliner) should fix your issues.
