### ISSUE TITLE
issue running align module with pandas 1.3.5

### ISSUE THREAD

**Issue by mollyguscott** [shahcompbio/single_cell_pipeline#207]
# Error

```bash 
pypeliner.helpers - ERROR - job_name /alignment_workflow/plot_metrics failed to complete
	 --- stdout ---
	--- stderr ---
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.7/site-packages/pypeliner/jobs.py", line 490, in __call__
	    ret_value = func(*callset.args, **callset.kwargs)
	  File "/opt/conda/lib/python3.7/site-packages/single_cell/workflows/align/tasks.py", line 22, in plot_metrics
	    plot.plot_alignment_metrics()
	  File "/opt/conda/lib/python3.7/site-packages/single_cell/utils/singlecell_copynumber_plot_utils/plot_metrics.py", line 848, in plot_alignment_metrics
	    df = self.sort_samples(df)
	  File "/opt/conda/lib/python3.7/site-packages/single_cell/utils/singlecell_copynumber_plot_utils/plot_metrics.py", line 500, in sort_samples
	    df = df.sort_index(by=['row', 'column'], ascending=[True, True])
	  File "/data/home/hfx865/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
	    return func(*args, **kwargs)
	TypeError: sort_index() got an unexpected keyword argument 'by'
2023-05-22 16:16:11,254 - pypeliner.scheduler - ERROR - exception
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.7/site-packages/pypeliner/scheduler.py", line 193, in _wait_next_job
	    raise IncompleteJobException()
	pypeliner.scheduler.IncompleteJobException
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/opt/conda/lib/python3.7/site-packages/pypeliner/scheduler.py", line 96, in run
	    self._wait_next_job(exec_queue, workflow)
	  File "/opt/conda/lib/python3.7/site-packages/pypeliner/scheduler.py", line 198, in _wait_next_job
	    self._handle_error(job, received.log_text(), "failed to complete\n", exec_queue)
	  File "/opt/conda/lib/python3.7/site-packages/pypeliner/scheduler.py", line 177, in _handle_error
	    raise pypeliner.graph.IncompleteJobException()
	pypeliner.graph.IncompleteJobException
```
# Problem

Seems to be an error with the version of the container which I am using, stems from an issue with the version of pandas

**Comment by diljotgrewal** [comment]
Hi,

We've stopped development on this project and have moved on to mondrian:
https://github.com/mondrian-scwgs/mondrian

Alignment workflow under mondrian has the same basic steps. 
Thanks!
